server.port = 5050

spring.datasource.url=jdbc:mysql://localhost/RajnishDemo_DB?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update